---
apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-cidr
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/upbound/function-cidr
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A HashiCorp compatible cidr calculation function for
      cidrhost, cidrnetmask. cidrsubnet. cidrsubmets.
    meta.crossplane.io/readme: |
      A HashiCorp compatible cidr calculation function for
      cidrhost, cidrnetmask. cidrsubnet. cidrsubmets.
spec:
  crossplane:
    version: ">=v1.14.0-up.1"
